name: build go linked to pico
on:
  push:
    branches: [main]
  pull_request:

env:
  DEBVER: svox-1.0+git20130326

jobs:

  pico-lib:
    name: Extract Pico package
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Source deb pkg
      run: |
          sudo cp third_party/deb.list /etc/apt/sources.list.d/
          sudo apt-get update
          apt-get source libttspico-utils

    - name: Build static lib (optional )
      run: |
          cd ${DEBVER}/pico/lib
          gcc -fPIC -g -c *.c
          ar rcs libpico.a *.o
    - name: Tarball
      run: |
          cd ${DEBVER}/pico
          tar -zcvf ../../test-files.tgz \
                    lib/libpico.a lib/*.h \
                    lang/en-GB_*.bin \
                    lang/PicoLangEnGBInSystem.mk \
                    lang/all_pico_languages.mk
    - name: Store tarball
      uses: actions/upload-artifact@v3
      with:
        name: static-lib
        retention-days: 1
        path: test-files.tgz

  build-it:
    name: Build binary
    needs: pico-lib
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.18.0'

    - name: Unshelve tarball
      uses: actions/download-artifact@v3
      with:
        name: static-lib
    - name: Unpack tarball
      run: tar -zxvf test-files.tgz
    - name: Bazel build
      run: |
          mv third_party/BUILD.pico lib/BUILD.bazel
          bazel build //...


